theme: minima
title: Day One of My Programming Journey
description: Learning Web Development. Starting my programming Journey with The Odin Project. After retiring from a 25-year career as a network engineer, I am looking forward to starting a new chapter in tech with full-stack web development. 
author: JoshuaGoth
